import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { FiHome, FiClipboard, FiPlusCircle, FiFileText, FiTruck, FiUser, FiDownload, FiAlertCircle } from "react-icons/fi";
import { DashboardLayout, PageHeader, StatCard } from "../components/DashboardLayout";
import { RouteGuard } from "../components/RouteGuard";
import { useAuth } from "../context/AuthContext";
import { getCustomerDashboard, listCustomerOrders, createCustomerOrder, getCustomerTimeline, getCustomerDocuments, listCustomerInvoices, listCustomerDeliveries, getCustomerProfile, updateCustomerProfile, downloadCustomerDocument } from "../services/customerPortalService";
import { listProducts } from "../services/productService";
import "../styles/forms.css";

export const Route = createFileRoute("/customer/dashboard")({ component: CustomerDashboard });
const SIDE=[{key:"dashboard",label:"Dashboard",icon:FiHome},{key:"orders",label:"Orders",icon:FiClipboard},{key:"new",label:"Place Order",icon:FiPlusCircle},{key:"invoices",label:"Invoices",icon:FiFileText},{key:"deliveries",label:"Deliveries",icon:FiTruck},{key:"profile",label:"Profile",icon:FiUser}];
const money=(v)=>Number(v||0).toLocaleString();
function CustomerDashboard(){return <RouteGuard allowedRoles={["CUSTOMER"]}><CustomerWorkspace/></RouteGuard>}
function CustomerWorkspace(){
 const { user }=useAuth();
 const [tab,setTab]=useState("dashboard"),[data,setData]=useState(null),[orders,setOrders]=useState([]),[invoices,setInvoices]=useState([]),[deliveries,setDeliveries]=useState([]),[products,setProducts]=useState([]),[profile,setProfile]=useState(null),[selected,setSelected]=useState(null),[timeline,setTimeline]=useState(null),[docs,setDocs]=useState([]),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const refresh=async()=>{try{const [d,o,i,dl,p,pr]=await Promise.all([getCustomerDashboard(),listCustomerOrders(),listCustomerInvoices(),listCustomerDeliveries(),listProducts({size:100}),getCustomerProfile()]);setData(d);setOrders(o||[]);setInvoices(i||[]);setDeliveries(dl||[]);setProducts((p.content||[]).map(x=>({...x,availableQuantity:undefined})));setProfile(pr)}catch(e){setError(e.message||"Unable to load your portal.")}};
 useEffect(()=>{refresh()},[]);
 const detail=async(o)=>{setSelected(o);try{const [t,d]=await Promise.all([getCustomerTimeline(o.id),getCustomerDocuments(o.id)]);setTimeline(t);setDocs(d||[])}catch(e){setError(e.message)}};
 const download=async(path,name)=>{try{const blob=await downloadCustomerDocument(path);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}catch(e){setError(e.message||"Document download failed.")}};
 const submit=async(e)=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await createCustomerOrder({productId:Number(fd.get("productId")),quantity:Number(fd.get("quantity")),deliveryAddress:fd.get("deliveryAddress"),destination:fd.get("destination"),paymentMethod:fd.get("paymentMethod"),notes:fd.get("notes")});setSuccess("Your order was submitted for Sales review.");e.currentTarget.reset();setTab("orders");refresh()}catch(e){setError(e.message||"Order could not be submitted.")}};
 const saveProfile=async(e)=>{e.preventDefault();try{const result=await updateCustomerProfile(profile);setProfile(result);setSuccess("Profile updated.")}catch(e){setError(e.message)}};
 const rows=(items,cols,render)=><div className="fef-panel"><div className="fef-table-wrap"><table className="fef-table"><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{items.map(render)}{!items.length&&<tr><td colSpan={cols.length} style={{textAlign:"center",padding:28}}>Nothing available yet.</td></tr>}</tbody></table></div></div>;
 const customerName=[user?.firstName,user?.lastName].filter(Boolean).join(" ")||user?.username||profile?.contactPerson||"Customer";
 return <DashboardLayout role="CUSTOMER" pageTitle={SIDE.find(x=>x.key===tab)?.label||"Customer Portal"} sideItems={SIDE} activeKey={tab} onSelect={setTab}>
  <PageHeader title={tab==="dashboard"?`Welcome, ${customerName}`:SIDE.find(x=>x.key===tab)?.label} crumbs={["Customer Portal"]}/>
  {error&&<div className="fef-alert fef-alert-danger"><FiAlertCircle/> {error}</div>}{success&&<div className="fef-alert fef-alert-success">{success}</div>}
  {tab==="dashboard"&&<><div className="fef-panel" style={{padding:20,marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><h3 style={{margin:0}}>{profile?.companyName||"Your company"}</h3><p style={{margin:"6px 0 0"}}>{profile?.customerCode} · {profile?.contactPerson||"Contact details pending"}</p><p style={{margin:"4px 0 0"}}>{profile?.email} {profile?.phone&&` · ${profile.phone}`}</p></div><button className="fef-btn fef-btn-primary" onClick={()=>setTab("new")}><FiPlusCircle/> Apply / Order Fuel</button></div></div><div className="fef-stat-grid"><StatCard label="Total Orders" value={data?.totalOrders??"…"} icon={FiClipboard} tone="primary"/><StatCard label="Active Orders" value={data?.activeOrders??"…"} icon={FiTruck} tone="warning"/><StatCard label="Awaiting Payment" value={data?.awaitingPayment??"…"} icon={FiFileText} tone="warning"/><StatCard label="In Transit" value={data?.inTransit??"…"} icon={FiTruck} tone="primary"/><StatCard label="Delivered" value={data?.delivered??"…"} icon={FiHome} tone="success"/></div><h3 style={{marginTop:28}}>Recent Orders</h3>{rows(data?.recentOrders||[],["Order","Fuel","Quantity","Amount","Status",""],o=><tr key={o.id}><td>{o.orderNumber}</td><td>{o.productName}</td><td>{money(o.quantity)} L</td><td>{money(o.totalAmount)}</td><td><span className="fef-badge fef-badge-info">{o.customerStatus}</span></td><td><button className="fef-btn fef-btn-outline" onClick={()=>{detail(o);setTab("detail")}}>View</button></td></tr>)}</>}
  {tab==="orders"&&<>{rows(orders,["Order","Fuel","Quantity","Total","Status",""],o=><tr key={o.id}><td>{o.orderNumber}</td><td>{o.productName}</td><td>{money(o.quantity)} L</td><td>{money(o.totalAmount)}</td><td>{o.customerStatus}</td><td><button className="fef-btn fef-btn-outline" onClick={()=>{detail(o);setTab("detail")}}>Details</button></td></tr>)}</>}
  {tab==="new"&&<form className="fef-panel" onSubmit={submit} style={{maxWidth:720,padding:24}}><div className="fef-form-grid"><label className="fef-label">Fuel product<select className="fef-input" name="productId" required>{products.filter(p=>p.status!=="DELETED").map(p=><option key={p.id} value={p.id}>{p.productName} — {money(p.unitPrice)} / litre</option>)}</select></label><label className="fef-label">Quantity (litres)<input className="fef-input" name="quantity" type="number" min="0.01" step="0.01" required/></label><label className="fef-label">Destination<input className="fef-input" name="destination" required/></label><label className="fef-label">Delivery address<input className="fef-input" name="deliveryAddress" required/></label><label className="fef-label">Payment method<select className="fef-input" name="paymentMethod"><option>Bank Transfer</option><option>Mobile Money</option><option>Cash on Delivery</option></select></label><label className="fef-label">Notes<textarea className="fef-input" name="notes"/></label></div><button className="fef-btn fef-btn-primary" style={{marginTop:20}}>Submit for Sales Review</button></form>}
  {tab==="invoices"&&rows(invoices,["Invoice","Order","Date","Amount","Payment",""],i=><tr key={i.id}><td>{i.invoiceNumber}</td><td>{i.orderNumber}</td><td>{i.invoiceDate?.slice(0,10)}</td><td>{money(i.grandTotal)}</td><td>{i.paymentStatus}</td><td><button className="fef-btn fef-btn-outline" onClick={()=>download(`/customer-portal/invoices/${i.id}/pdf`,`${i.invoiceNumber}.pdf`)}><FiDownload/> PDF</button></td></tr>)}
  {tab==="deliveries"&&rows(deliveries,["Delivery","Order","Truck","Destination","Status","Date"],d=><tr key={d.id}><td>{d.deliveryNumber}</td><td>{d.orderNumber}</td><td>{d.truckNumber||"Assigned"}</td><td>{d.destination}</td><td>{d.deliveryStatus}</td><td>{d.dispatchedAt?.slice(0,10)||"—"}</td></tr>)}
  {tab==="profile"&&profile&&<form className="fef-panel" onSubmit={saveProfile} style={{maxWidth:720,padding:24}}><p><strong>{profile.companyName}</strong> · {profile.customerCode}</p><div className="fef-form-grid"><label className="fef-label">Contact person<input className="fef-input" value={profile.contactPerson||""} onChange={e=>setProfile({...profile,contactPerson:e.target.value})}/></label><label className="fef-label">Email<input className="fef-input" type="email" value={profile.email||""} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label className="fef-label">Phone<input className="fef-input" value={profile.phone||""} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label className="fef-label">Address<textarea className="fef-input" value={profile.address||""} onChange={e=>setProfile({...profile,address:e.target.value})}/></label></div><button className="fef-btn fef-btn-primary" style={{marginTop:20}}>Save profile</button></form>}
  {tab==="detail"&&selected&&<div className="fef-panel" style={{padding:24}}><button className="fef-btn fef-btn-outline" onClick={()=>setTab("orders")}>Back to Orders</button><h2>{selected.orderNumber}</h2><p>{selected.productName} · {money(selected.quantity)} L · {selected.customerStatus}</p><h3>Order progress</h3>{timeline?.steps?.map(s=><div key={s.key} style={{padding:"8px 0",color:s.current?"var(--feftms-primary)":s.complete?"var(--feftms-success)":"var(--feftms-text-muted)",fontWeight:s.current?700:400}}>{s.complete?"✓":s.current?"●":"○"} {s.label}</div>)}<h3 style={{marginTop:20}}>Documents</h3>{docs.map(d=><p key={`${d.type}-${d.id}`}><button className="fef-btn fef-btn-outline" onClick={()=>download(d.endpoint,`${d.number}.pdf`)}><FiDownload/> {d.type}: {d.number}</button></p>)}{!docs.length&&<p>No customer documents are available yet.</p>}</div>}
 </DashboardLayout>
}
