import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { FiDownload, FiEye, FiFileText, FiPrinter, FiTruck, FiCheckCircle, FiAlertCircle, FiArrowLeft, FiCompass, FiUserCheck, FiX } from "react-icons/fi";
import { DashboardLayout, PageHeader, StatCard } from "../components/DashboardLayout";
import { RouteGuard } from "../components/RouteGuard";
import { OperatorWorkflowProgress } from "../components/OperatorWorkflowProgress";
import { listLoadingOrders } from "../services/loadingOrderService";
import { getDeliveryNote, getPaymentReceiptForOrder, handDeliveryNoteToDriver, printDeliveryNote } from "../services/deliveryDocumentService";
import falconLogo from "../assets/falcon-logo.png";
import "../styles/forms.css";

export const Route = createFileRoute("/delivery-documents")({ component: DeliveryDocumentsWorkspace });
const SIDE = [{ key: "operations", label: "Operations", icon: FiArrowLeft }, { key: "docs", label: "Delivery Documents", icon: FiFileText }, { key: "dispatch", label: "Dispatch Management", icon: FiTruck }, { key: "deliveries", label: "Delivery Management", icon: FiCompass }];
const fmt = (value) => value == null || value === "" ? "—" : typeof value === "number" ? value.toLocaleString() : value;
const date = (value) => value ? new Date(value).toLocaleString() : "—";

function documentSpec(kind, doc) {
  if (kind === "note") return { title: "DELIVERY NOTE", number: doc.deliveryNoteNumber, status: doc.status, sections: [["Customer & destination", [["Customer", doc.customerName], ["Destination", doc.destination], ["Prepared", date(doc.preparedAt)]]], ["Truck & loading", [["Truck", doc.truckNumber], ["Driver", doc.driverName], ["Carrier", doc.transportCompany], ["Product", doc.productName], ["Ambient volume", `${fmt(doc.ambientVolume)} L`], ["Standard volume @20°C", `${fmt(doc.standardVolume)} L`]]]] };
  if (kind === "receipt") return { title: "PAYMENT RECEIPT", number: doc.receiptNumber, status: "PAID", company: doc.companyName, sections: [["Receipt information", [["Receipt date", date(doc.generatedAt)], ["Payment date", date(doc.receivedAt)], ["Payment confirmation", date(doc.paymentConfirmedAt)], ["Invoice number", doc.invoiceNumber], ["Invoice date", date(doc.invoiceDate)], ["Customer order", doc.customerOrderNumber]]], ["Customer information", [["Company", doc.customerCompany], ["Contact person", doc.customerContactPerson], ["Contact number", doc.customerContact], ["Email", doc.customerEmail]]], ["Order information", [["Fuel product", doc.productName], ["Fuel quantity", `${fmt(doc.fuelQuantity)} L`]]], ["Payment information", [["Total amount paid", `${doc.currency || ""} ${fmt(doc.receivedAmount)}`], ["Payment method", doc.paymentMethod], ["Transaction reference", doc.paymentReference], ["Bank", doc.bankName], ["Payment status", "PAID — Full settlement"]]], ["Payment summary", [["Fuel charges", `${doc.currency || ""} ${fmt(doc.fuelSupplyAmount)}`], ["Transport charges", `${doc.currency || ""} ${fmt(doc.transportChargeAmount)} (included in invoice)`], ["Total paid", `${doc.currency || ""} ${fmt(doc.receivedAmount)}`]]], ["Related documents", [["Loading order", doc.loadingOrderNumber], ["Loading report", doc.loadingReportNumber], ["Delivery note", doc.deliveryNoteNumber]]], ["Finance information", [["Finance officer", doc.financeOfficerName], ["Received by", doc.receivedBy], ["Generated", date(doc.generatedAt)]]]] };
  return null;
}

function DocumentBody({ kind, doc }) {
  const spec = documentSpec(kind, doc);
  return <div className="fef-print-area" style={{ color: "#17213b", background: "#fff", padding: 32, fontFamily: "Inter, Arial, sans-serif" }}>
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "3px solid #0d4598", paddingBottom: 16 }}><div style={{ display: "flex", alignItems: "center", gap: 14 }}><img src={falconLogo} alt="Falcon Energy" style={{ width: 58, height: 58, objectFit: "contain" }} /><div><div style={{ color: "#0d4598", fontSize: 22, fontWeight: 800, letterSpacing: ".5px" }}>{spec.company || "FALCON ENERGY LTD."}</div><div style={{ color: "#64748b", fontSize: 11 }}>{kind === "receipt" ? `${doc.companyAddress} · ${doc.companyPhone} · ${doc.companyEmail}` : "Fuel Trading Management System"}</div></div></div><div style={{ textAlign: "right" }}><div style={{ fontWeight: 800, fontSize: 17 }}>{spec.title}</div><div style={{ color: "#0d4598", fontWeight: 700, marginTop: 4 }}>{spec.number}</div><span style={{ display: "inline-block", marginTop: 7, padding: "3px 9px", background: "#e8f5ed", color: "#15803d", borderRadius: 12, fontSize: 10, fontWeight: 800 }}>{spec.status}</span></div></div>
    {spec.sections.map(([heading, rows]) => <section key={heading} style={{ marginTop: 24 }}><h4 style={{ color: "#0d4598", margin: "0 0 8px", fontSize: 13, textTransform: "uppercase", letterSpacing: ".6px" }}>{heading}</h4><div style={{ border: "1px solid #dbe3ef", borderRadius: 5, overflow: "hidden" }}>{rows.map(([label, value], i) => <div key={label} style={{ display: "grid", gridTemplateColumns: "190px 1fr", padding: "10px 13px", background: i % 2 ? "#f8fafc" : "#fff", fontSize: 13 }}><strong style={{ color: "#475569" }}>{label}</strong><span>{fmt(value)}</span></div>)}</div></section>)}
    {kind === "receipt" && <div style={{ marginTop: 22, padding: 14, borderLeft: "4px solid #15803d", background: "#f0fdf4", fontSize: 12, lineHeight: 1.55 }}><strong>Full settlement confirmed.</strong> This receipt confirms full payment of Invoice {doc.invoiceNumber}, including fuel supply and transport charges. No outstanding balance remains for this order.</div>}
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 45, marginTop: 55, fontSize: 11, textAlign: "center" }}><div style={{ borderTop: "1px solid #64748b", paddingTop: 8 }}>Prepared / Authorized by Falcon Energy</div><div style={{ borderTop: "1px solid #64748b", paddingTop: 8 }}>Driver / Receiver acknowledgement</div></div>
    <div style={{ marginTop: 28, paddingTop: 12, borderTop: "1px solid #dbe3ef", color: "#64748b", fontSize: 10, textAlign: "center" }}>System-generated Falcon Energy document · {spec.number}</div>
  </div>;
}

function DeliveryDocumentsWorkspace() {
  const navigate = useNavigate(); const [activities, setActivities] = useState([]); const [documents, setDocuments] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [preview, setPreview] = useState(null);
  const load = async () => { try { setLoading(true); const orders = await listLoadingOrders(); const rows = orders.flatMap(o => (o.activities || []).filter(a => a.status === "COMPLETED").map(a => ({ ...a, orderId: o.orderId, loadingOrderNumber: o.loadingOrderNumber, customerName: o.customerName }))); setActivities(rows); const next = {}; await Promise.all(rows.map(async a => { next[a.id] = {}; await Promise.all([getDeliveryNote(a.id).then(x => next[a.id].note = x).catch(() => {}), getPaymentReceiptForOrder(a.orderId).then(x => next[a.id].receipt = x).catch(() => {})]); })); setDocuments(next); } catch { setError("Failed to load delivery documents."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const printableHtml = (kind, doc) => { const s = documentSpec(kind, doc); const settlement = kind === "receipt" ? `<p><b>This receipt confirms full payment of Invoice ${doc.invoiceNumber}. The invoice, including fuel charges and transport charges, has been fully settled.</b></p>` : ""; return `<!doctype html><html><head><meta charset="utf-8"><title>${s.title} ${s.number}</title><style>body{font:14px Arial;color:#17213b;margin:40px}.head{display:flex;justify-content:space-between;border-bottom:3px solid #0d4598;padding-bottom:16px}h1{color:#0d4598;font-size:24px;margin:0}h3{color:#0d4598;margin-top:28px;font-size:14px}.number{font-weight:bold;color:#0d4598}.status{color:#15803d;font-weight:bold}table{border-collapse:collapse;width:100%}td{padding:10px 13px;border:1px solid #dbe3ef}td:first-child{font-weight:bold;color:#475569;width:35%;background:#f8fafc}.foot{margin-top:55px;text-align:center;border-top:1px solid #64748b;padding-top:8px}</style></head><body><div class="head"><div><h1>${s.company || "FALCON ENERGY LTD."}</h1><small>${kind === "receipt" ? `${doc.companyAddress} · ${doc.companyPhone} · ${doc.companyEmail}` : "Fuel Trading Management System"}</small></div><div style="text-align:right"><b>${s.title}</b><br><span class="number">${s.number}</span><br><span class="status">${s.status}</span></div></div>${s.sections.map(([h, rows]) => `<h3>${h}</h3><table>${rows.map(([k,v]) => `<tr><td>${k}</td><td>${fmt(v)}</td></tr>`).join("")}</table>`).join("")}${settlement}<div class="foot">System-generated Falcon Energy document · ${s.number}</div></body></html>`; };
  const replaceDeliveryNote = (noteId, updatedNote) => setDocuments(current => Object.fromEntries(Object.entries(current).map(([activityId, docs]) => [activityId, docs?.note?.id === noteId ? { ...docs, note: updatedNote } : docs])));
  const print = async (kind, doc) => { try { setError(""); const updatedNote = kind === "note" ? await printDeliveryNote(doc.id) : null; if (updatedNote) { replaceDeliveryNote(doc.id, updatedNote); doc = updatedNote; } const w = window.open("", "_blank"); w.document.write(printableHtml(kind, doc)); w.document.close(); w.focus(); w.print(); } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to print this document."); } };
  const handToDriver = async (doc) => { try { setError(""); const updatedNote = await handDeliveryNoteToDriver(doc.id); replaceDeliveryNote(doc.id, updatedNote); } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to mark the Delivery Note as handed to the driver."); } };
  const download = (kind, doc) => { const s = documentSpec(kind, doc); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([printableHtml(kind, doc)], { type: "text/html" })); link.download = `${s.title.replaceAll(" ", "-")}-${s.number}.html`; link.click(); URL.revokeObjectURL(link.href); };
  const action = (title, kind, doc) => doc ? <div style={{ display: "flex", gap: 5, flexWrap: "wrap", alignItems: "center" }}><button className="fef-btn fef-btn-outline" style={{ padding: "4px 7px", fontSize: 11 }} onClick={() => setPreview({ kind, doc })}><FiEye /> View</button><button className="fef-btn fef-btn-outline" style={{ padding: "4px 7px", fontSize: 11 }} onClick={() => print(kind, doc)}><FiPrinter /> Print</button><button className="fef-btn fef-btn-outline" style={{ padding: "4px 7px", fontSize: 11 }} onClick={() => download(kind, doc)}><FiDownload /> Download</button>{kind === "note" && doc.status !== "HANDED_TO_DRIVER" && <button className="fef-btn fef-btn-success" style={{ padding: "4px 7px", fontSize: 11 }} disabled={doc.status !== "PRINTED"} title={doc.status !== "PRINTED" ? "Print the Delivery Note before handing it to the driver." : "Confirm the printed Delivery Note has been handed to the driver."} onClick={() => handToDriver(doc)}><FiUserCheck /> Hand to Driver</button>}{kind === "note" && doc.status === "HANDED_TO_DRIVER" && <span className="fef-badge fef-badge-success">HANDED TO DRIVER</span>}</div> : <span className="fef-badge fef-badge-pending">PENDING</span>;
  const ready = activities.filter(a => { const d=documents[a.id]; return d?.note && d?.receipt; }).length;
  return <RouteGuard allowedRoles={["OPERATIONS", "ADMIN", "OPERATOR"]}>
    <DashboardLayout role="OPERATIONS" sideItems={SIDE} activeKey="docs" onSelect={k => k === "operations" ? navigate({to:"/operations"}) : k === "dispatch" ? navigate({to:"/dispatch"}) : k === "deliveries" ? navigate({to:"/deliveries"}) : null}>
      <PageHeader title="Delivery Documents" crumbs={["Operations", "Delivery Documents"]} />
      <OperatorWorkflowProgress current="Documentation" nextLabel="Dispatch Management" onNext={() => navigate({to:"/dispatch"})} />
      {error && <div className="fef-alert fef-alert-danger"><FiAlertCircle /> {error}</div>}
      <div className="fef-stat-grid"><StatCard label="Completed Loadings" value={loading ? "…" : activities.length} icon={FiTruck} tone="primary" /><StatCard label="Documents Ready" value={loading ? "…" : ready} icon={FiCheckCircle} tone="success" /><StatCard label="Awaiting Documents" value={loading ? "…" : activities.length-ready} icon={FiFileText} tone="warning" /></div>
      <div className="fef-panel" style={{marginTop:24}}><div className="fef-panel-head"><h3>Automatically Generated Delivery Documents</h3></div><div className="fef-table-wrap"><table className="fef-table"><thead><tr><th>Truck / Customer</th><th>Delivery Note</th><th>Payment Receipt</th></tr></thead><tbody>{activities.map(a => <tr key={a.id}><td><strong>{a.truckNumber}</strong><div style={{fontSize:11,color:"var(--feftms-text-muted)"}}>{a.customerName} · {a.loadingOrderNumber}</div></td><td>{action("Delivery Note", "note", documents[a.id]?.note)}</td><td>{action("Payment Receipt", "receipt", documents[a.id]?.receipt)}</td></tr>)}{!loading && !activities.length && <tr><td colSpan="3" style={{textAlign:"center",padding:30}}>No completed detailed loading reports are awaiting delivery documents.</td></tr>}</tbody></table></div></div>
      {preview && typeof window !== "undefined" && createPortal(<div className="fef-modal-backdrop" onClick={() => setPreview(null)}><div className="fef-modal-window" style={{maxWidth:820}} onClick={e => e.stopPropagation()}><button className="fef-modal-close" onClick={() => setPreview(null)}><FiX /></button><DocumentBody {...preview} /><div style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:16}}><button className="fef-btn fef-btn-outline" onClick={() => download(preview.kind, preview.doc)}><FiDownload /> Download</button><button className="fef-btn fef-btn-primary" onClick={() => print(preview.kind, preview.doc)}><FiPrinter /> Print</button></div></div></div>, document.body)}
    </DashboardLayout>
  </RouteGuard>;
}
