import { useEffect, useMemo, useState } from "react";
import L from "leaflet";
import { MapContainer, Marker, Polyline, TileLayer, useMap, useMapEvents } from "react-leaflet";
import "leaflet/dist/leaflet.css";
import { reverseGeocode, searchLocations } from "../services/geocodingService";

const DEFAULT_CENTER = [-6.1659, 39.2026];
const pin = L.divIcon({ className: "", html: '<div style="background:#0f766e;border:3px solid white;box-shadow:0 1px 5px #334155;border-radius:50% 50% 50% 0;width:20px;height:20px;transform:rotate(-45deg)"></div>', iconSize: [24, 24], iconAnchor: [12, 24] });
const validPoint = (point) => point?.latitude !== "" && point?.latitude != null && point?.longitude !== "" && point?.longitude != null && Number.isFinite(Number(point.latitude)) && Number.isFinite(Number(point.longitude));
function decodePolyline(encoded) { let index=0, latitude=0, longitude=0; const points=[]; while (encoded && index<encoded.length) { let shift=0,result=0,byte; do { byte=encoded.charCodeAt(index++)-63; result|=(byte&31)<<shift; shift+=5; } while(byte>=32&&index<encoded.length); latitude+=result&1?~(result>>1):result>>1; shift=0;result=0; do { byte=encoded.charCodeAt(index++)-63; result|=(byte&31)<<shift; shift+=5; } while(byte>=32&&index<encoded.length); longitude+=result&1?~(result>>1):result>>1; points.push([latitude/1e5,longitude/1e5]); } return points; }
function Recenter({ center, route }) { const map=useMap(); useEffect(()=>{ if(route.length>1) map.fitBounds(route,{padding:[24,24]}); else map.setView(center, validPoint({latitude:center[0],longitude:center[1]})?14:11); },[map,center,route]); return null; }
function ClickToSelect({ onPoint }) { useMapEvents({ click:(event)=>onPoint(event.latlng.lat,event.latlng.lng) }); return null; }

export function OpenStreetMapLocationPickerClient({ value, onChange, routePreview, disabled, searchLabel = "Search delivery location", selectedLabel = "Selected location", placeholder = "Search address or place" }) {
 const [query,setQuery]=useState(value?.address||""),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const route=useMemo(()=>decodePolyline(routePreview?.polyline),[routePreview?.polyline]); const center=validPoint(value)?[Number(value.latitude),Number(value.longitude)]:DEFAULT_CENTER;
 useEffect(()=>setQuery(value?.address||""),[value?.address]);
 useEffect(()=>{const trimmed=query.trim();if(trimmed.length<3||(value?.address&&trimmed===value.address)){setResults([]);setLoading(false);return undefined;}let active=true;const controller=new AbortController();const timer=window.setTimeout(async()=>{if(!active)return;setLoading(true);setError("");try{const found=await searchLocations(trimmed,controller.signal);if(active)setResults(found);}catch(exception){if(active&&exception.name!=="CanceledError"&&exception.name!=="AbortError")setError(exception.message||"Location search is unavailable.");}finally{if(active)setLoading(false);}},500);return()=>{active=false;window.clearTimeout(timer);controller.abort();};},[query,value?.address]);
 const select=(location)=>{setQuery(location.address);setResults([]);setError("");onChange(location);};
 const selectPoint=async(latitude,longitude)=>{setLoading(true);setError("");try{select(await reverseGeocode(latitude,longitude));}catch(exception){select({latitude,longitude,address:"Selected map location"});}finally{setLoading(false);}};
 return <div><label className="fef-label">{searchLabel}<input className="fef-input" disabled={disabled} value={query} onChange={(event)=>{setQuery(event.target.value);setError("");}} placeholder={placeholder} autoComplete="off"/></label>{(loading||results.length>0)&&<div style={{position:"relative",zIndex:1000}}><div style={{position:"absolute",width:"100%",background:"white",border:"1px solid #d1d5db",borderRadius:8,boxShadow:"0 8px 18px rgba(15,23,42,.12)",maxHeight:180,overflow:"auto"}}>{loading&&<p style={{margin:10}}>Searching locations…</p>}{!loading&&results.map((result)=><button type="button" key={`${result.latitude},${result.longitude}`} onClick={()=>select(result)} style={{display:"block",textAlign:"left",width:"100%",border:0,borderBottom:"1px solid #e5e7eb",background:"white",padding:10,cursor:"pointer"}}>{result.address}</button>)}{!loading&&!results.length&&!error&&query.trim().length>=3&&<p style={{margin:10}}>No locations found. Try a more specific search or select the map.</p>}</div></div>}<MapContainer center={center} zoom={validPoint(value)?14:11} style={{height:300,width:"100%",marginTop:10,borderRadius:10,overflow:"hidden",background:"#e5e7eb"}}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Recenter center={center} route={route}/><ClickToSelect onPoint={selectPoint}/>{route.length>1&&<Polyline positions={route} pathOptions={{color:"#0f766e",weight:5}}/>}{validPoint(value)&&<Marker position={center} icon={pin} draggable={!disabled} eventHandlers={{dragend:(event)=>{const point=event.target.getLatLng();selectPoint(point.lat,point.lng);}}}/>}</MapContainer>{validPoint(value)&&<p style={{margin:"10px 0 0"}}>📍 <strong>{selectedLabel}:</strong> {value.address}<br/><small>{Number(value.latitude).toFixed(6)}, {Number(value.longitude).toFixed(6)}</small></p>}{error&&<p style={{margin:"10px 0 0",color:"var(--feftms-danger)"}}>{error}</p>}</div>;
}
