package com.falconenergy.service.impl;
import com.falconenergy.dto.*; import com.falconenergy.entity.FuelProduct; import com.falconenergy.entity.TransportPriceRange; import com.falconenergy.exception.*; import com.falconenergy.repository.FuelProductRepository; import com.falconenergy.repository.TransportPriceRangeRepository; import com.falconenergy.service.TransportPriceRangeService; import lombok.RequiredArgsConstructor; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor @Transactional public class TransportPriceRangeServiceImpl implements TransportPriceRangeService { private final TransportPriceRangeRepository repo; private final FuelProductRepository fuelProducts;
 public List<TransportPriceRangeResponse> all(){return repo.findAll().stream().map(this::map).toList();}
 public TransportPriceRangeResponse create(TransportPriceRangeRequest r){validate(r,null); TransportPriceRange x=TransportPriceRange.builder().fuelProduct(product(r.getFuelProductId())).minLitres(r.getMinLitres()).maxLitres(r.getMaxLitres()).transportPrice(r.getTransportPrice()).effectiveDate(r.getEffectiveDate()).status(status(r.getStatus())).build(); audit(x,true); return map(repo.save(x));}
 public TransportPriceRangeResponse update(Long id,TransportPriceRangeRequest r){TransportPriceRange x=find(id);validate(r,id);x.setFuelProduct(product(r.getFuelProductId()));x.setMinLitres(r.getMinLitres());x.setMaxLitres(r.getMaxLitres());x.setTransportPrice(r.getTransportPrice());x.setEffectiveDate(r.getEffectiveDate());x.setStatus(status(r.getStatus()));audit(x,false);return map(repo.save(x));}
 public TransportPriceRangeResponse toggle(Long id){TransportPriceRange x=find(id);x.setStatus("ACTIVE".equals(x.getStatus())?"INACTIVE":"ACTIVE");audit(x,false);return map(repo.save(x));}
 public void delete(Long id){repo.delete(find(id));}
 @Transactional(readOnly=true) public BigDecimal resolve(FuelProduct product, BigDecimal litres){List<TransportPriceRange> xs=repo.matches(product.getId(),litres,LocalDate.now());if(xs.isEmpty())throw new BadRequestException("No active transport pricing has been configured for the selected fuel product and ordered litre quantity. Please contact Finance.");if(xs.size()>1)throw new BadRequestException("More than one active transport price matches the selected fuel product and ordered litre quantity. Please contact Finance.");return xs.getFirst().getTransportPrice();}
 private void validate(TransportPriceRangeRequest r,Long id){if(r.getMinLitres().compareTo(r.getMaxLitres())>0)throw new BadRequestException("Minimum ordered litres cannot exceed maximum ordered litres.");if(repo.overlaps(r.getFuelProductId(),r.getMinLitres(),r.getMaxLitres(),id))throw new BadRequestException("This ordered litre range overlaps an existing transport pricing range for the selected fuel product.");}
 private FuelProduct product(Long id){return fuelProducts.findById(id).orElseThrow(()->new ResourceNotFoundException("Fuel product not found with id: "+id));} private TransportPriceRange find(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Transport price range not found with id: "+id));} private String status(String s){String x=s==null?"ACTIVE":s.toUpperCase();if(!Set.of("ACTIVE","INACTIVE").contains(x))throw new BadRequestException("Status must be ACTIVE or INACTIVE.");return x;} private void audit(TransportPriceRange x,boolean create){String a=SecurityContextHolder.getContext().getAuthentication()==null?"system":SecurityContextHolder.getContext().getAuthentication().getName();if(create){x.setCreatedBy(a);x.setCreatedAt(LocalDateTime.now());}x.setUpdatedBy(a);x.setUpdatedAt(LocalDateTime.now());} private TransportPriceRangeResponse map(TransportPriceRange x){return TransportPriceRangeResponse.builder().id(x.getId()).fuelProductId(x.getFuelProduct()==null?null:x.getFuelProduct().getId()).fuelProductName(x.getFuelProduct()==null?null:x.getFuelProduct().getProductName()).minLitres(x.getMinLitres()).maxLitres(x.getMaxLitres()).transportPrice(x.getTransportPrice()).effectiveDate(x.getEffectiveDate()).status(x.getStatus()).createdBy(x.getCreatedBy()).createdAt(x.getCreatedAt()).updatedAt(x.getUpdatedAt()).build();}}
