/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as ViewerRouteImport } from "./routes/viewer";
import { Route as SalesRouteImport } from "./routes/sales";
import { Route as OperationsRouteImport } from "./routes/operations";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as LoadingRouteImport } from "./routes/loading";
import { Route as FinanceRouteImport } from "./routes/finance";
import { Route as DriverRouteImport } from "./routes/driver";
import { Route as DispatchRouteImport } from "./routes/dispatch";
import { Route as CustomerServiceRouteImport } from "./routes/customer-service";
import { Route as CustomerRouteImport } from "./routes/customer";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";

const ViewerRoute = ViewerRouteImport.update({
  id: "/viewer",
  path: "/viewer",
  getParentRoute: () => rootRouteImport,
});
const SalesRoute = SalesRouteImport.update({
  id: "/sales",
  path: "/sales",
  getParentRoute: () => rootRouteImport,
});
const OperationsRoute = OperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const LoadingRoute = LoadingRouteImport.update({
  id: "/loading",
  path: "/loading",
  getParentRoute: () => rootRouteImport,
});
const FinanceRoute = FinanceRouteImport.update({
  id: "/finance",
  path: "/finance",
  getParentRoute: () => rootRouteImport,
});
const DriverRoute = DriverRouteImport.update({
  id: "/driver",
  path: "/driver",
  getParentRoute: () => rootRouteImport,
});
const DispatchRoute = DispatchRouteImport.update({
  id: "/dispatch",
  path: "/dispatch",
  getParentRoute: () => rootRouteImport,
});
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: "/customer-service",
  path: "/customer-service",
  getParentRoute: () => rootRouteImport,
});
const CustomerRoute = CustomerRouteImport.update({
  id: "/customer",
  path: "/customer",
  getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CustomerRoute: CustomerRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  DispatchRoute: DispatchRoute,
  DriverRoute: DriverRoute,
  FinanceRoute: FinanceRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  SalesRoute: SalesRoute,
  ViewerRoute: ViewerRoute,
};

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
