/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DeliveryDocumentsRouteImport } from './routes/delivery-documents'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminManagementRouteImport } from './routes/admin-management'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryDocumentsRoute = DeliveryDocumentsRouteImport.update({
  id: '/delivery-documents',
  path: '/delivery-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManagementRoute = AdminManagementRouteImport.update({
  id: '/admin-management',
  path: '/admin-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-management': typeof AdminManagementRoute
  '/customer': typeof CustomerRoute
  '/customer-service': typeof CustomerServiceRoute
  '/deliveries': typeof DeliveriesRoute
  '/delivery-documents': typeof DeliveryDocumentsRoute
  '/dispatch': typeof DispatchRoute
  '/driver': typeof DriverRoute
  '/finance': typeof FinanceRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-management': typeof AdminManagementRoute
  '/customer': typeof CustomerRoute
  '/customer-service': typeof CustomerServiceRoute
  '/deliveries': typeof DeliveriesRoute
  '/delivery-documents': typeof DeliveryDocumentsRoute
  '/dispatch': typeof DispatchRoute
  '/driver': typeof DriverRoute
  '/finance': typeof FinanceRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-management': typeof AdminManagementRoute
  '/customer': typeof CustomerRoute
  '/customer-service': typeof CustomerServiceRoute
  '/deliveries': typeof DeliveriesRoute
  '/delivery-documents': typeof DeliveryDocumentsRoute
  '/dispatch': typeof DispatchRoute
  '/driver': typeof DriverRoute
  '/finance': typeof FinanceRoute
  '/loading': typeof LoadingRoute
  '/login': typeof LoginRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/viewer': typeof ViewerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-management'
    | '/customer'
    | '/customer-service'
    | '/deliveries'
    | '/delivery-documents'
    | '/dispatch'
    | '/driver'
    | '/finance'
    | '/loading'
    | '/login'
    | '/operations'
    | '/reports'
    | '/sales'
    | '/viewer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-management'
    | '/customer'
    | '/customer-service'
    | '/deliveries'
    | '/delivery-documents'
    | '/dispatch'
    | '/driver'
    | '/finance'
    | '/loading'
    | '/login'
    | '/operations'
    | '/reports'
    | '/sales'
    | '/viewer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-management'
    | '/customer'
    | '/customer-service'
    | '/deliveries'
    | '/delivery-documents'
    | '/dispatch'
    | '/driver'
    | '/finance'
    | '/loading'
    | '/login'
    | '/operations'
    | '/reports'
    | '/sales'
    | '/viewer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminManagementRoute: typeof AdminManagementRoute
  CustomerRoute: typeof CustomerRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  DeliveriesRoute: typeof DeliveriesRoute
  DeliveryDocumentsRoute: typeof DeliveryDocumentsRoute
  DispatchRoute: typeof DispatchRoute
  DriverRoute: typeof DriverRoute
  FinanceRoute: typeof FinanceRoute
  LoadingRoute: typeof LoadingRoute
  LoginRoute: typeof LoginRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  ViewerRoute: typeof ViewerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-documents': {
      id: '/delivery-documents'
      path: '/delivery-documents'
      fullPath: '/delivery-documents'
      preLoaderRoute: typeof DeliveryDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-management': {
      id: '/admin-management'
      path: '/admin-management'
      fullPath: '/admin-management'
      preLoaderRoute: typeof AdminManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminManagementRoute: AdminManagementRoute,
  CustomerRoute: CustomerRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  DeliveriesRoute: DeliveriesRoute,
  DeliveryDocumentsRoute: DeliveryDocumentsRoute,
  DispatchRoute: DispatchRoute,
  DriverRoute: DriverRoute,
  FinanceRoute: FinanceRoute,
  LoadingRoute: LoadingRoute,
  LoginRoute: LoginRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  ViewerRoute: ViewerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
